title: Objnews
theme: jekyll-theme-minimal
baseurl: "/objnews"
collections:
  articles:
    output: true
    permalink: /:title/

defaults:
  - scope:
      path: ""
      type: "articles"
    values:
      layout: "default"
