title: Objnews
theme: jekyll-theme-minimal

collections:
  articles:
    output: true
    permalink: /:title/ # This makes the URL objnews.com/first-post/ (cleaner)

defaults:
  - scope:
      path: ""
      type: "articles"
    values:
      layout: "default" # This saves you from typing 'layout: default' in every file
